# FROM ubuntu
FROM python:3.10-slim-buster

WORKDIR /workspace
COPY model-train/train.py /workspace/
COPY ./model-train/requirements.txt /workspace/

RUN pip install --no-cache-dir -r requirements.txt

# CMD ["python" , "train.py"]
# create dockerfile here
